# Generated by Django 6.0.5 on 2026-05-09 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAgentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Pergunta")),
                (
                    "detected_intent",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Intenção detectada"
                    ),
                ),
                (
                    "generated_sql",
                    models.TextField(blank=True, verbose_name="SQL gerada"),
                ),
                (
                    "validation_sql",
                    models.TextField(
                        blank=True, verbose_name="SQL de validação cruzada"
                    ),
                ),
                (
                    "sql_result_preview",
                    models.TextField(blank=True, verbose_name="Preview do resultado"),
                ),
                (
                    "final_answer",
                    models.TextField(blank=True, verbose_name="Resposta final"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Sucesso"),
                            ("error", "Erro"),
                            ("partial", "Parcial"),
                            ("ambiguous", "Ambíguo"),
                        ],
                        default="success",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensagem de erro"),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        default=0, verbose_name="Tempo de execução (ms)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_agent_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log do Agente IA",
                "verbose_name_plural": "Logs do Agente IA",
                "ordering": ["-created_at"],
            },
        ),
    ]
