# Generated by Django 6.0.5 on 2026-05-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0003_port_knowledge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portbusinessrule',
            options={'ordering': ['priority', 'rule_name'], 'verbose_name': 'Regra de Negócio Portuária', 'verbose_name_plural': 'Regras de Negócio Portuárias'},
        ),
        migrations.AlterModelOptions(
            name='portglossary',
            options={'ordering': ['term'], 'verbose_name': 'Glossário Portuário', 'verbose_name_plural': 'Glossário Portuário'},
        ),
        migrations.AlterModelOptions(
            name='portknowledgebase',
            options={'ordering': ['priority', '-updated_at'], 'verbose_name': 'Conhecimento Portuário', 'verbose_name_plural': 'Base de Conhecimento Portuário'},
        ),
        migrations.AlterField(
            model_name='aiagentfeedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiagentlearning',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portbusinessrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portbusinessrule',
            name='priority',
            field=models.IntegerField(default=5, help_text='1 = maior prioridade'),
        ),
        migrations.AlterField(
            model_name='portglossary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portknowledgebase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portknowledgebase',
            name='priority',
            field=models.IntegerField(default=5, help_text='1 = maior prioridade, 10 = menor'),
        ),
        migrations.AlterField(
            model_name='useraipreferences',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useraipreferences',
            name='preferred_date_field',
            field=models.CharField(blank=True, default='data_desatracacao', help_text='Campo de data preferido para filtros temporais', max_length=100),
        ),
    ]
