BEGIN;

CREATE TABLE IF NOT EXISTS atracacoes_navio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_atracacao VARCHAR(50) NOT NULL,
    berco VARCHAR(100) NOT NULL,
    navio VARCHAR(255) NOT NULL,
    imo VARCHAR(20),
    agencia VARCHAR(255),
    cliente VARCHAR(255),
    eta TIMESTAMP,
    etb TIMESTAMP,
    nor TIMESTAMP,
    atracacao TIMESTAMP,
    inicio_operacao TIMESTAMP,
    termino_operacao TIMESTAMP,
    desatracacao TIMESTAMP,
    comprimento DECIMAL(10, 2),
    largura DECIMAL(10, 2),
    dwt DECIMAL(14, 2),
    calado_entrada DECIMAL(6, 2),
    calado_saida DECIMAL(6, 2),
    status VARCHAR(50) NOT NULL DEFAULT 'planejada',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cargas_atracacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atracacao_id BIGINT NOT NULL,
    nome_carga VARCHAR(255) NOT NULL,
    natureza_tipo VARCHAR(100),
    natureza_subtipo VARCHAR(100),
    operacao VARCHAR(100),
    sentido VARCHAR(50),
    operador VARCHAR(255),
    quantidade_toneladas DECIMAL(14, 3),
    plr VARCHAR(100),
    prancha INTEGER,
    observacao TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cargas_atracacao_atracacao
        FOREIGN KEY (atracacao_id)
        REFERENCES atracacoes_navio (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_atracacoes_navio_imo
    ON atracacoes_navio (imo);

CREATE INDEX IF NOT EXISTS idx_atracacoes_navio_berco
    ON atracacoes_navio (berco);

CREATE INDEX IF NOT EXISTS idx_atracacoes_navio_atracacao
    ON atracacoes_navio (atracacao);

CREATE INDEX IF NOT EXISTS idx_cargas_atracacao_nome_carga
    ON cargas_atracacao (nome_carga);

CREATE INDEX IF NOT EXISTS idx_cargas_atracacao_atracacao_id
    ON cargas_atracacao (atracacao_id);

COMMENT ON TABLE atracacoes_navio IS
    'Armazena informacoes das atracacoes de navios em operacoes portuarias.';

COMMENT ON COLUMN atracacoes_navio.id IS 'Identificador unico da atracacao.';
COMMENT ON COLUMN atracacoes_navio.numero_atracacao IS 'Numero operacional ou codigo da atracacao.';
COMMENT ON COLUMN atracacoes_navio.berco IS 'Berco portuario utilizado pela embarcacao.';
COMMENT ON COLUMN atracacoes_navio.navio IS 'Nome da embarcacao.';
COMMENT ON COLUMN atracacoes_navio.imo IS 'Codigo IMO da embarcacao.';
COMMENT ON COLUMN atracacoes_navio.agencia IS 'Agencia maritima responsavel.';
COMMENT ON COLUMN atracacoes_navio.cliente IS 'Cliente associado a operacao.';
COMMENT ON COLUMN atracacoes_navio.eta IS 'Data e hora estimada de chegada.';
COMMENT ON COLUMN atracacoes_navio.etb IS 'Data e hora estimada de atracacao.';
COMMENT ON COLUMN atracacoes_navio.nor IS 'Notice of Readiness: data e hora de prontidao do navio, sempre menor ou igual a atracacao.';
COMMENT ON COLUMN atracacoes_navio.atracacao IS 'Data e hora efetiva de atracacao.';
COMMENT ON COLUMN atracacoes_navio.inicio_operacao IS 'Data e hora de inicio da operacao.';
COMMENT ON COLUMN atracacoes_navio.termino_operacao IS 'Data e hora de termino da operacao.';
COMMENT ON COLUMN atracacoes_navio.desatracacao IS 'Data e hora efetiva de desatracacao.';
COMMENT ON COLUMN atracacoes_navio.comprimento IS 'Comprimento total da embarcacao em metros.';
COMMENT ON COLUMN atracacoes_navio.largura IS 'Largura da embarcacao em metros.';
COMMENT ON COLUMN atracacoes_navio.dwt IS 'Porte bruto da embarcacao em toneladas.';
COMMENT ON COLUMN atracacoes_navio.calado_entrada IS 'Calado de entrada da embarcacao em metros.';
COMMENT ON COLUMN atracacoes_navio.calado_saida IS 'Calado de saida da embarcacao em metros.';
COMMENT ON COLUMN atracacoes_navio.status IS 'Status atual da atracacao.';
COMMENT ON COLUMN atracacoes_navio.created_at IS 'Data e hora de criacao do registro.';
COMMENT ON COLUMN atracacoes_navio.updated_at IS 'Data e hora da ultima atualizacao do registro.';

COMMENT ON TABLE cargas_atracacao IS
    'Armazena as cargas vinculadas a cada atracacao de navio.';

COMMENT ON COLUMN cargas_atracacao.id IS 'Identificador unico da carga vinculada a atracacao.';
COMMENT ON COLUMN cargas_atracacao.atracacao_id IS 'Referencia para a atracacao proprietaria da carga.';
COMMENT ON COLUMN cargas_atracacao.nome_carga IS 'Nome ou descricao principal da carga.';
COMMENT ON COLUMN cargas_atracacao.natureza_tipo IS 'Tipo de natureza da carga.';
COMMENT ON COLUMN cargas_atracacao.natureza_subtipo IS 'Subtipo de natureza da carga.';
COMMENT ON COLUMN cargas_atracacao.operacao IS 'Tipo de operacao realizada com a carga.';
COMMENT ON COLUMN cargas_atracacao.sentido IS 'Sentido da movimentacao da carga.';
COMMENT ON COLUMN cargas_atracacao.operador IS 'Operador responsavel pela movimentacao da carga.';
COMMENT ON COLUMN cargas_atracacao.quantidade_toneladas IS 'Quantidade movimentada em toneladas.';
COMMENT ON COLUMN cargas_atracacao.plr IS 'Identificador ou referencia PLR da carga.';
COMMENT ON COLUMN cargas_atracacao.prancha IS 'Produtividade operacional da mercadoria em toneladas por hora, com valor inteiro entre 300 e 1042.';
COMMENT ON COLUMN cargas_atracacao.observacao IS 'Observacoes adicionais sobre a carga.';
COMMENT ON COLUMN cargas_atracacao.created_at IS 'Data e hora de criacao do registro.';
COMMENT ON COLUMN cargas_atracacao.updated_at IS 'Data e hora da ultima atualizacao do registro.';

COMMIT;
